# 1. Build the Docker image
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/watchful-scope-473414-p3/app-repo/hello-app:latest'
      - '.'

  # 2. Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/watchful-scope-473414-p3/app-repo/hello-app:latest'

  # 3. Authenticate to GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud container clusters get-credentials hello-cluster \
          --region us-central1 \
          --project $PROJECT_ID

        # Apply all YAMLs
        kubectl apply -f deployment.yaml

images:
  - 'us-central1-docker.pkg.dev/watchful-scope-473414-p3/app-repo/hello-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: "jenkins-ci-sa@watchful-scope-473414-p3.iam.gserviceaccount.com"

