apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: hello-app-pipeline
description: Main pipeline for hello-app
serialPipeline:
  stages:
    - targetId: dev
      profiles: []
    - targetId: prod
      profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: dev cluster
gke:
  cluster: projects/watchful-scope-473414-p3/locations/us-central1/clusters/hello-cluster
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: prod cluster
gke:
  cluster: projects/watchful-scope-473414-p3/locations/us-central1/clusters/prod-cluster

